[package]
name = "robinson"
version = "0.0.1"
authors = ["Matt Brubeck <mbrubeck@limpet.net>"]
edition = "2018"

[[bin]]
name = "robinson"
path = "src/main.rs"

[dependencies]
getopts = "0.2"
image = "0.14"
